site_name: Dr. Inventor Text Mining Framework Documentation
repo_url: https://github.com/fra82/driframeworkclient
repo_name: GitHub
theme: readthedocs
site_description: Documentation for Dr. Inventor Text Mining Framework
docs_dir: doc
include_search: true
nav:
- Home: 'index.md'
- About:
    - 'Introduction': 'Introduction.md'
    - 'References': 'References.md'
    - 'Version': 'Version.md'
- Architecture:
    - 'Overview': 'ArchitectureOverview.md'
    - 'Converting PDF to text': 'PDFtoText.md'
    - 'Analyzing citations': 'Citation.md'
    - 'Identifying the rhetorical role of sentences': 'RhetSentence.md'
    - 'Annotating papers by Babelnet': 'BabelnetAnn.md'
    - 'Generating Subject-Verb-Object graphs': 'SVOgraph.md'
    - 'Summarizing papers': 'Summa.md'
- User manual:
    - 'Installation': 'Installation.md'
    - 'Initialization': 'Initialize.md'
    - 'Import scientific publications': 'ImportDoc.md'
    - 'Process scientific publications': 'ProcessDoc.md'
    - 'The Scientific Publication Data Model': 'ScuPubDataModel.md'
    - 'Store processing results': 'StoreDoc.md'
    - 'FAQ': 'FAQ.md'
